name: 新機能
description: 新機能の提案
projects: "djkazunoko/1"
assignees:
  - djkazunoko
body:
  - type: textarea
    attributes: 
      label: 機能の説明
    validations:
      required: true
  - type: textarea
    attributes: 
      label: 何故この機能が必要なのか
    validations:
      required: true
  - type: textarea
    attributes: 
      label: 完了条件
    validations:
      required: true
  - type: textarea
    attributes: 
      label: 参考
  - type: textarea
    attributes: 
      label: その他
